### ISSUE TITLE
Deprecation error on [@octokit/request-error]

### ISSUE THREAD

**Issue by razvanonet** [softprops/aws-credential-rotary#10]
We're using this github action to rotate our AWS credentials but got into a problem with rotating organisation level secrets. we're am able to rotate repository level secrets.

This is the build step setup that we have:
     - name: Rotate AWS credentials
        uses: softprops/aws-credential-rotary@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_KEYS_ROTATION_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ORG_LEVEL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_ORG_LEVEL }}
        with:
          github-access-key-id-name: 'AWS_ACCESS_KEY_ID_ORG_LEVEL'
          github-secret-access-key-name: 'AWS_SECRET_ACCESS_KEY_ID_ORG_LEVEL'
          organization: 'orgname'

This is the error that we get, and it looks like there's a problem with @octokit/request-error

Deprecation: [@octokit/request-error] 'error.headers' is deprecated, use error.response.headers.
    at RequestError.get (/home/runner/work/_actions/softprops/aws-credential-rotary/v0.1.1/dist/index.js:7:67890)
    at /home/runner/work/_actions/softprops/aws-credential-rotary/v0.1.1/dist/index.js:28:225510
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
}
{
  'access-control-allow-origin': '*',
  'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
  connection: 'close',
  'content-length': '376',
  'content-security-policy': "default-src 'none'",
  'content-type': 'application/json; charset=utf-8',
  date: 'Mon, 16 Aug 2021 09:11:44 GMT',
  'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
  server: 'GitHub.com',
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
  vary: 'Accept-Encoding, Accept, X-Requested-With',
  'x-accepted-oauth-scopes': 'admin:org',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-github-media-type': 'github.v3; format=json',
  'x-github-request-id': '0484:1915:4462CC:861FAA:611A2BCF',
  'x-oauth-scopes': 'admin:org, repo, workflow',
  'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4978',
  'x-ratelimit-reset': '1629106077',
  'x-ratelimit-resource': 'core',
  'x-ratelimit-used': '22',
  'x-xss-protection': '0'
}
Error: Invalid request.

For 'items', "381315435" is not an integer.
For 'items', "389972912" is not an integer.
For 'items', "381315757" is not an integer.

**Comment by softprops** [comment]
I've not used the organization level feature myself. Support was added in https://github.com/softprops/aws-credential-rotary/pull/6 . @ulich have you seen this in your usage?

**Comment by ulich** [comment]
No, we haven't seen this error yet. The only difference I see from how we use this action is that we use the default secret names:

```
      - name: Rotate credentials
        uses: softprops/aws-credential-rotary@v0.1.1
        with:
          iam-user-name: "github.actions"
          organization: "orgname"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Could you maybe try it out with the default secret names @razvanonet?

**Comment by razvanonet** [comment]
yesss, it works with the default ones. This is how I've used it. 

```
      - name: Rotate AWS credentials
        uses: softprops/aws-credential-rotary@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_KEYS_ROTATION_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          organization: 'orgname'
```
