### ISSUE TITLE
Cannot write new github org secret

### ISSUE THREAD

**Issue by scott-doyland-burrows** [softprops/aws-credential-rotary#11]
Hi,

I have my workflow defined to update an org secret, but get this error when I run it:

```
Run softprops/aws-credential-rotary@v1
  with:
    github-access-key-id-name: SCOTT_ID
    github-secret-access-key-name: SCOTT_PASS
    organization: [redacted]
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_REGION: eu-west-2
    ORGANIZATION: [redacted]
    GITHUB_TOKEN: ***
Checking current credentials
Provisoning new access key
Fetching public key
Upserting secret SCOTT_ID
failed to upsert secret SCOTT_ID for [redacted]
Deprecation: [@octokit/request-error] `error.headers` is deprecated, use `error.response.headers`.
    at RequestError.get (/home/runner/work/_actions/softprops/aws-credential-rotary/v1/dist/index.js:7:67890)
    at /home/runner/work/_actions/softprops/aws-credential-rotary/v1/dist/index.js:28:225510
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
}
{
  'access-control-allow-origin': '*',
  'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
  connection: 'close',
  'content-length': '188',
  'content-security-policy': "default-src 'none'",
  'content-type': 'application/json; charset=utf-8',
  date: 'Tue, 14 Dec 2021 13:45:27 GMT',
  'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
  server: 'GitHub.com',
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
  vary: 'Accept-Encoding, Accept, X-Requested-With',
  'x-accepted-oauth-scopes': 'admin:org',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-github-media-type': 'github.v3; format=json',
  'x-github-request-id': '0403:5594:5AAC06:BC8106:61B89FF7',
  'x-oauth-scopes': 'admin:org, repo, workflow',
  'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4989',
  'x-ratelimit-reset': '1639492235',
  'x-ratelimit-resource': 'core',
  'x-ratelimit-used': '11',
  'x-xss-protection': '0'
}
Error: Invalid request.

For 'items', "436670825" is not an integer.
```

The workflow is:

```
name: test
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SCOTT_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SCOTT_PASS }}
  AWS_REGION: eu-west-2
  ORGANIZATION: [redacted]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          GITHUB_TOKEN=`aws secretsmanager get-secret-value --secret-id [redacted] --query SecretString --output text`
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      - run: echo "::add-mask::$GITHUB_TOKEN"
      - uses: softprops/aws-credential-rotary@v1
        with:
          github-access-key-id-name: SCOTT_ID
          github-secret-access-key-name: SCOTT_PASS
          organization: ${{ env.ORGANIZATION }}
```
